language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - redis-server

before_script:
  - psql -c 'create database online_judge_travis;' -U postgres

script: "npm run-script test_travis"